import StoreProvider from "@/app/redux/StoreProvider";
import { Poppins } from "next/font/google";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import Footer from "./components/Footer";
import Header from "./components/Header";
import Navbar from "./components/Navbar";
import "./globals.css";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600"],
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html className={poppins.className}>
      <body>
        <StoreProvider>
          <Header />
          <Navbar />
          {children}
        </StoreProvider>
        <Footer />
        <ToastContainer />
        {/* <CartSideBar /> */}
      </body>
    </html>
  );
}
